import Head from 'next/head'
import EntryForm from './conponents/EntryForm.jsx'
import Bkg from "./conponents/bkg.jsx"
import { Flex } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Happy Birthday</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex h="100%" minH={"100vh"} height={"100%"} w="100%">
        <Bkg />
        <EntryForm />
      </Flex>
    </>
  )
}
